{{- if .Values.dbApp.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.dbApp.name | quote }}
  labels:
    {{- include "otus-hw-app.labels.db" . | nindent 4 }}
data:
  POSTGRES_DB: postgresdb
{{- end }}