apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.dbApp.name }}
  labels:
    {{- include "otus-hw-app.labels.db" . | nindent 4 }}
data:
  POSTGRES_USER: YWRtaW4=
  POSTGRES_PASSWORD: dGVzdDEyMw==
