apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{ include "otus-hw-app.fullname" . }}-monitor"
  labels:
    {{- include "otus-hw-app.labels.server" . | nindent 4 }}
spec:
  endpoints:
    - port: http
      scheme: http
      path: /metrics
      interval: 10s
  selector:
    matchLabels:
      {{- include "otus-hw-app.selectorLabels.server" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace | quote }}