apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otus-hw-app.fullname" . }}
  labels:
    {{- include "otus-hw-app.labels.server" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.serverDeployment.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "otus-hw-app.selectorLabels.server" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "otus-hw-app.labels.server" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "otus-hw-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.serverDeployment.image.repository }}:{{ .Values.serverDeployment.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.serverDeployment.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          {{- if .Values.dbApp.enabled }}
          envFrom:
            - configMapRef:
                name: {{ .Values.serverApp.name | quote }}
            - configMapRef:
                name: {{ .Values.dbApp.name | quote }}
            - secretRef:
                name: {{ .Values.dbApp.name | quote }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
