imagePullSecrets: []
nameOverride: "otus-hw-app"
fullnameOverride: "otus-hw-app"

serviceAccount:
  create: false
  annotations: {}
  name: ""

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts:
    - host: arch.homework
      paths:
        - path: /(.*)
          pathType: ImplementationSpecific
        - path: /otusapp/iabashin/(.*)
          pathType: ImplementationSpecific
  tls: []

serverApp:
  additionalLabels:
    app.domain: server

serverDeployment:
  replicaCount: 3
  image:
    repository: abashin/otus-hw-server
    pullPolicy: IfNotPresent
    tag: 0.3.0

serverService:
  type: ClusterIP
  port: 80
  targetPort: 8000

migratorJob:
  image:
    repository: abashin/otus-hw-migrator:0.3.0
    pullPolicy: IfNotPresent
    tag: 0.3.0

dbApp:
  enabled: true
  name: postgres
  additionalLabels:
    app.domain: db

dbStatefulSet:
  replicas: 1
  image:
    name: postgres
    pullPolicy: IfNotPresent
    version: 14.4
  container:
    name: postgres
    port: 5432
  serviceName: postgres-headless

dbPV:
  labels:
    type: local
  volumeMode: Filesystem
  accessMode: ReadWriteMany
  storageSize: 5Gi

dbPVC: ~

dbConfigMap: ~

dbService:
  enabled: true
  name: postgres
  type: ClusterIP
  port: 5432
  targetPort: 5432

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
