{{- if .Values.dbApp.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.dbApp.name | quote }}
  labels:
    {{- include "otus-hw-server.labels" . | nindent 4 }}
    {{- toYaml .Values.dbApp.labels | nindent 4 }}
data:
  POSTGRES_DB: postgresdb
{{- end }}