apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrations
  labels:
    {{- include "otus-hw-server.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: db-migration
      labels:
        {{- include "otus-hw-server.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: db-migrator
          image: {{ .Values.migratorJob.image.repository }}:{{ .Values.migratorJob.image.tag }}
          imagePullPolicy: {{ .Values.migratorJob.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Values.dbApp.name | quote }}
            - secretRef:
                name: {{ .Values.dbApp.name | quote }}
          command:
            - /app
            - up
  backoffLimit: 5
