apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.dbApp.name }}
  labels:
    {{- include "otus-hw-server.labels" . | nindent 4 }}
    {{- toYaml .Values.dbApp.labels | nindent 4 }}
data:
  POSTGRES_USER: YWRtaW4=
  POSTGRES_PASSWORD: dGVzdDEyMw==
